export const CHANGE_LEVEL = 'CHANGE_LEVEL'
export const SET_WORD = 'SET_WORD'
export const SET_CURRENT = 'SET_CURRENT'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const UPDATE_SCORE = 'UPDATE_SCORE'